### ISSUE TITLE
Cannot find ref files.

### ISSUE THREAD

**Issue by b4sh5i** [bananabr/ulua#2]
I saw that your blog.
I need to put the lua binary in the ref directory using luci(https://github.com/openwrt/luci) .
but i dont understand how can make lua binary.. can i help you?

**Comment by b4sh5i** [comment]
```
mkdir ./sample/; find ./squashfs-root/usr/lib/lua/luci/ -iname “*.lua” -exec cp {} ./sample/ \;
mkdir ./ref/; find openwrt-luci/libs/ -iname “*.lua” -exec bash -c ‘luac -o ./ref/`basename {}` {}’ \;
```
can not check this point xD sry

**Comment by bananabr** [comment]
Glad you figure that out =)
